export const FIND_PRODUCT_BY_ID_REQUEST = 'FIND_PRODUCT_BY_ID_REQUES'
export const FIND_PRODUCT_BY_ID_SUCCES = 'FIND_PRODUCT_BY_ID_SUCCES'
export const FIND_PRODUCT_BY_ID_FAILURE = 'FIND_PRODUCT_BY_ID_FAILURE'

export const FIND_PRODUCTS_REQUEST = 'FIND_PRODUCT_BY_CATEGORY_REQUES'
export const FIND_PRODUCTS_SUCCES = 'FIND_PRODUCT_BY_CATEGORY_SUCCES'
export const FIND_PRODUCTS_FAILURE = 'FIND_PRODUCT_BY_CATEGORY_FAILURE'